site_name: Dirk's Wiki
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - tables
  - toc
plugins:
  - search